### ISSUE TITLE
Possible improvements - allow setting a default volume

### ISSUE THREAD

**Issue by Leroy439** [ThePredators/FlutterVolumeSlider#2]
Dear developer,
Thanks for this package. I like it's simplicity.
Is it possible to allow one to set a default volume for the app it's being used in?
It would be good to have setting persistence and be able to retrieve the current volume setting.
Thanks a lot.
Leroy439

**Comment by ThePredators** [comment]
hello @Leroy439 

I didnt understand what you mean by set a default volume for the App ?

You can do that by changing the value of : initVal
